# General configuration for inference using a pre-trained model

root_dir: ${oc.env:PWD}
mode: inference  # Mode of operation (e.g., inference, evaluation)

# Paths
paths:
  # model_path: /path/to/model  # Path to the pre-trained model
  model_path: ${root_dir}/models/AUTO_IHU_INT_100_rounds_1_epoch.pt
  output_dir: ${root_dir}/results/  # Directory to save inference results

# Data configuration
data:
  name: pbr
  config:
    # dir_test: /path/to/test/data  # Directory containing test data
    dir_test: ${root_dir}/datasets/ProstateRectum_Bladder/Federated/INT/holdout
    batch_size: 1
    num_workers: 4 # Number of workers for data loading
    cache_rate: 0.0

# Model configuration
model:
  name: unet            # Name of the model
  config:
    spatial_dims: 3
    in_channels: 1
    out_channels: 4
    channels: [16, 32, 64, 128, 256]
    strides: [2, 2, 2, 2]
    num_res_units: 2
    norm: BATCH
    patch_size: [96, 96, 96]
    save_dir: ${paths.output_dir}  # Directory to save model outputs

# Fabric configuration
fabric:
  accelerator: gpu      # Type of accelerator to use (e.g., gpu, cpu, auto)
  devices: auto         # Number of devices or "auto" to let Fabric decide